import { db } from '@/lib/firebase';
import {
  collection,
  addDoc,
  serverTimestamp,
  getDocs,
} from 'firebase/firestore';
import { toast } from 'sonner';
import { Task } from '@/lib/task-firestore'; // Import Task interface

// Function to seed initial tasks
export const seedInitialTasks = async () => {
  const tasksCollectionRef = collection(db, 'tasks');
  const snapshot = await getDocs(tasksCollectionRef);

  if (snapshot.empty) {
    console.log("Database is empty, seeding initial tasks...");
    const initialTasks = [
      {
        title: "Tubero for leaky sink – ₱500",
        category: "repairs",
        description: "Need a plumber to fix a leaky sink in the kitchen. Small job, but needs to be done quickly.",
        location: "Quezon City, Metro Manila",
        budget: 500,
        posterId: "seed-client-1",
        posterName: "Aling Nena",
        posterAvatar: "https://randomuser.me/api/portraits/women/68.jpg",
        datePosted: serverTimestamp(),
        status: "open",
        imageUrl: "https://images.unsplash.com/photo-1581578731548-c646952?ixlib=rb-4.0.3&auto=format&fit=crop&w=500&q=80",
      },
      {
        title: "General Cleaning for Apartment – ₱800",
        category: "cleaning",
        description: "Thorough cleaning for a 2-bedroom apartment. Includes kitchen, bathroom, living room, and bedrooms.",
        location: "Makati City, Metro Manila",
        budget: 800,
        posterId: "seed-client-2",
        posterName: "Mang Tonyo",
        posterAvatar: "https://randomuser.me/api/portraits/men/32.jpg",
        datePosted: serverTimestamp(),
        status: "open",
        imageUrl: "https://images.unsplash.com/photo-1581578731548-c646952?ixlib=rb-4.0.3&auto=format&fit=crop&w=500&q=80",
      },
      {
        title: "Delivery Service for Documents – ₱200",
        category: "delivery",
        description: "Urgent document delivery from Pasig to Taguig. Must be reliable and fast.",
        location: "Pasig City, Metro Manila",
        budget: 200,
        posterId: "seed-client-3",
        posterName: "Liza Soberano",
        posterAvatar: "https://randomuser.me/api/portraits/women/2.jpg",
        datePosted: serverTimestamp(),
        status: "open",
        imageUrl: "https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?ixlib=rb-4.0.3&auto=format&fit=crop&w=500&q=80",
      },
      {
        title: "Electrician for outlet repair – ₱1,200",
        category: "repairs",
        description: "Need an electrician to fix a faulty electrical outlet in the living room. Safety first!",
        location: "Mandaluyong City, Metro Manila",
        budget: 1200,
        posterId: "seed-client-4",
        posterName: "Daniel Padilla",
        posterAvatar: "https://randomuser.me/api/portraits/men/4.jpg",
        datePosted: serverTimestamp(),
        status: "open",
        imageUrl: "https://images.unsplash.com/photo-1581093458791-8a6b5d174d6c?ixlib=rb-4.0.3&auto=format&fit=crop&w=500&q=80",
      },
      {
        title: "Aircon Cleaning – ₱1,000",
        category: "cleaning",
        description: "Cleaning for one split-type air conditioner unit. Needs to be done this weekend.",
        location: "Quezon City, Metro Manila",
        budget: 1000,
        posterId: "seed-client-5",
        posterName: "Kathryn Bernardo",
        posterAvatar: "https://randomuser.me/api/portraits/women/6.jpg",
        datePosted: serverTimestamp(),
        status: "open",
        imageUrl: "https://images.unsplash.com/photo-1599669454699-248893623440?ixlib=rb-4.0.3&auto=format&fit=crop&w=500&q=80",
      },
      {
        title: "Carpentry for custom shelf – ₱1,500",
        category: "assembly",
        description: "Build a small custom wooden shelf for books. Materials provided.",
        location: "Pasig City, Metro Manila",
        budget: 1500,
        posterId: "seed-client-6",
        posterName: "Alden Richards",
        posterAvatar: "https://randomuser.me/api/portraits/men/8.jpg",
        datePosted: serverTimestamp(),
        status: "open",
        imageUrl: "https://images.unsplash.com/photo-1541976590-713941681591?ixlib=rb-4.0.3&auto=format&fit=crop&w=500&q=80",
      },
      {
        title: "Appliance Repair (Washing Machine) – ₱1,300",
        category: "repairs",
        description: "Washing machine not spinning. Need a technician to diagnose and repair.",
        location: "Taguig City, Metro Manila",
        budget: 1300,
        posterId: "seed-client-7",
        posterName: "Maine Mendoza",
        posterAvatar: "https://randomuser.me/api/portraits/women/10.jpg",
        datePosted: serverTimestamp(),
        status: "open",
        imageUrl: "https://images.unsplash.com/photo-1581093458791-8a6b5d174d6c?ixlib=rb-4.0.3&auto=format&fit=crop&w=500&q=80",
      },
      {
        title: "Painting Job for Bedroom – ₱2,000",
        category: "painting",
        description: "Paint one bedroom (approx. 10sqm). White paint, walls only. Paint provided.",
        location: "Cebu City",
        budget: 2000,
        posterId: "seed-client-8",
        posterName: "Coco Martin",
        posterAvatar: "https://randomuser.me/api/portraits/men/12.jpg",
        datePosted: serverTimestamp(),
        status: "open",
        imageUrl: "https://images.unsplash.com/photo-1541976590-713941681591?ixlib=rb-4.0.3&auto=format&fit=crop&w=500&q=80",
      },
      {
        title: "Laptop Fix (Screen Replacement) – ₱700",
        category: "repairs",
        description: "Broken laptop screen. Need someone experienced in laptop repairs.",
        location: "Davao City",
        budget: 700,
        posterId: "seed-client-9",
        posterName: "Angel Locsin",
        posterAvatar: "https://randomuser.me/api/portraits/women/14.jpg",
        datePosted: serverTimestamp(),
        status: "open",
        imageUrl: "https://images.unsplash.com/photo-1581093458791-8a6b5d174d6c?ixlib=rb-4.0.3&auto=format&fit=crop&w=500&q=80",
      },
      {
        title: "Plumbing Emergency (Clogged Toilet) – ₱600",
        category: "repairs",
        description: "Clogged toilet, urgent repair needed. Available immediately.",
        location: "Muntinlupa City, Metro Manila",
        budget: 600,
        posterId: "seed-client-10",
        posterName: "Vice Ganda",
        posterAvatar: "https://randomuser.me/api/portraits/men/16.jpg",
        datePosted: serverTimestamp(),
        status: "open",
        imageUrl: "https://images.unsplash.com/photo-1581578731548-c646952?ixlib=rb-4.0.3&auto=format&fit=crop&w=500&q=80",
      },
      {
        title: "House Helper for Weekly Chores – ₱900",
        category: "cleaning",
        description: "Looking for a house helper for weekly cleaning and light chores. 4 hours per session.",
        location: "Pasay City, Metro Manila",
        budget: 900,
        posterId: "seed-client-1",
        posterName: "Aling Nena",
        posterAvatar: "https://randomuser.me/api/portraits/women/68.jpg",
        datePosted: serverTimestamp(),
        status: "open",
        imageUrl: "https://images.unsplash.com/photo-1581578731548-c646952?ixlib=rb-4.0.3&auto=format&fit=crop&w=500&q=80",
      },
      {
        title: "Tutor for Math (Grade 6) – ₱500",
        category: "other", // Assuming 'other' for tutoring
        description: "Need a math tutor for a Grade 6 student. Focus on algebra basics. Online or in-person.",
        location: "Remote (Philippines)",
        budget: 500,
        posterId: "seed-client-2",
        posterName: "Mang Tonyo",
        posterAvatar: "https://randomuser.me/api/portraits/men/32.jpg",
        datePosted: serverTimestamp(),
        status: "open",
        imageUrl: "https://images.unsplash.com/photo-1504711432028-ee2611f5817a?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=500&q=80",
      },
      {
        title: "Grocery Delivery from SM – ₱250",
        category: "delivery",
        description: "Deliver groceries from SM Supermarket to my home. List will be provided.",
        location: "Quezon City, Metro Manila",
        budget: 250,
        posterId: "seed-client-3",
        posterName: "Liza Soberano",
        posterAvatar: "https://randomuser.me/api/portraits/women/2.jpg",
        datePosted: serverTimestamp(),
        status: "open",
        imageUrl: "https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?ixlib=rb-4.0.3&auto=format&fit=crop&w=500&q=80",
      },
      {
        title: "Office Cleaning (Small Office) – ₱1,800",
        category: "cleaning",
        description: "Deep cleaning for a small office space. Includes vacuuming, dusting, and sanitizing.",
        location: "Ortigas Center, Pasig City",
        budget: 1800,
        posterId: "seed-client-4",
        posterName: "Daniel Padilla",
        posterAvatar: "https://randomuser.me/api/portraits/men/4.jpg",
        datePosted: serverTimestamp(),
        status: "open",
        imageUrl: "https://images.unsplash.com/photo-1581578731548-c646952?ixlib=rb-4.0.3&auto=format&fit=crop&w=500&q=80",
      },
      {
        title: "Motorcycle Mechanic for Tune-up – ₱1,100",
        category: "repairs",
        description: "Motorcycle tune-up and oil change. Can bring to mechanic's shop or home service.",
        location: "Caloocan City, Metro Manila",
        budget: 1100,
        posterId: "seed-client-5",
        posterName: "Kathryn Bernardo",
        posterAvatar: "https://randomuser.me/api/portraits/women/6.jpg",
        datePosted: serverTimestamp(),
        status: "open",
        imageUrl: "https://images.unsplash.com/photo-1581093458791-8a6b5d174d6c?ixlib=rb-4.0.3&auto=format&fit=crop&w=500&q=80",
      },
      // Example of an assigned task
      {
        title: "Install new ceiling fan",
        category: "assembly",
        description: "Need help installing a new ceiling fan in the living room. Electrical knowledge required.",
        location: "Mandaluyong City, Metro Manila",
        budget: 750,
        posterId: "seed-client-6",
        posterName: "Alden Richards",
        posterAvatar: "https://randomuser.me/api/portraits/men/8.jpg",
        datePosted: serverTimestamp(),
        status: "assigned",
        imageUrl: "https://images.unsplash.com/photo-1541976590-713941681591?ixlib=rb-4.0.3&auto=format&fit=crop&w=500&q=80",
        assignedTaskerId: "seed-tasker-1", // Assigned to a dummy tasker
        assignedOfferId: "dummy-offer-1",
      },
      // Example of a completed task with rating and review
      {
        title: "Repair broken cabinet door",
        category: "repairs",
        description: "Cabinet door hinge is broken, needs to be replaced and re-aligned.",
        location: "Pasig City, Metro Manila",
        budget: 400,
        posterId: "seed-client-7",
        posterName: "Maine Mendoza",
        posterAvatar: "https://randomuser.me/api/portraits/women/10.jpg",
        datePosted: serverTimestamp(),
        status: "completed",
        imageUrl: "https://images.unsplash.com/photo-1541976590-713941681591?ixlib=rb-4.0.3&auto=format&fit=crop&w=500&q=80",
        assignedTaskerId: "seed-tasker-2", // Assigned to a dummy tasker
        assignedOfferId: "dummy-offer-2",
        rating: 5,
        review: "⭐⭐⭐⭐⭐ Solid si Kuya! Mabilis gumawa, sulit bayad. Highly recommended!",
      },
      {
        title: "Deep Clean Kitchen",
        category: "cleaning",
        description: "Thorough deep cleaning of kitchen including oven, fridge, and cabinets.",
        location: "Taguig City, Metro Manila",
        budget: 1500,
        posterId: "seed-client-8",
        posterName: "Coco Martin",
        posterAvatar: "https://randomuser.me/api/portraits/men/12.jpg",
        datePosted: serverTimestamp(),
        status: "completed",
        imageUrl: "https://images.unsplash.com/photo-1581578731548-c646952?ixlib=rb-4.0.3&auto=format&fit=crop&w=500&q=80",
        assignedTaskerId: "seed-tasker-2",
        assignedOfferId: "dummy-offer-3",
        rating: 4,
        review: "⭐⭐⭐⭐ Magaling maglinis, medyo matagal lang dumating. Pero overall, satisfied!",
      },
      {
        title: "Assemble IKEA Bookshelf",
        category: "assembly",
        description: "Need help assembling a large IKEA bookshelf. All tools provided.",
        location: "Quezon City, Metro Manila",
        budget: 800,
        posterId: "seed-client-9",
        posterName: "Angel Locsin",
        posterAvatar: "https://randomuser.me/api/portraits/women/14.jpg",
        datePosted: serverTimestamp(),
        status: "completed",
        imageUrl: "https://images.unsplash.com/photo-1541976590-713941681591?ixlib=rb-4.0.3&auto=format&fit=crop&w=500&q=80",
        assignedTaskerId: "seed-tasker-1",
        assignedOfferId: "dummy-offer-4",
        rating: 5,
        review: "⭐⭐⭐⭐⭐ Ang bilis at ang galing mag-assemble! Walang problema. Salamat!",
      },
      {
        title: "Dog Walking (Daily for a week)",
        category: "other",
        description: "Need someone to walk my golden retriever daily for one week, 30 mins each walk.",
        location: "Mandaluyong City, Metro Manila",
        budget: 1000,
        posterId: "seed-client-10",
        posterName: "Vice Ganda",
        posterAvatar: "https://randomuser.me/api/portraits/men/16.jpg",
        datePosted: serverTimestamp(),
        status: "completed",
        imageUrl: "https://images.unsplash.com/photo-1599669454699-248893623440?ixlib=rb-4.0.3&auto=format&fit=crop&w=500&q=80",
        assignedTaskerId: "seed-tasker-10",
        assignedOfferId: "dummy-offer-5",
        rating: 5,
        review: "⭐⭐⭐⭐⭐ Super bait sa aso ko! Very reliable. Will book again!",
      },
      {
        title: "Fix Leaky Faucet in Bathroom",
        category: "repairs",
        description: "Bathroom faucet is constantly dripping. Need a quick fix.",
        location: "Pasig City, Metro Manila",
        budget: 400,
        posterId: "seed-client-1",
        posterName: "Aling Nena",
        posterAvatar: "https://randomuser.me/api/portraits/women/68.jpg",
        datePosted: serverTimestamp(),
        status: "completed",
        imageUrl: "https://images.unsplash.com/photo-1581578731548-c646952?ixlib=rb-4.0.3&auto=format&fit=crop&w=500&q=80",
        assignedTaskerId: "seed-tasker-1",
        assignedOfferId: "dummy-offer-6",
        rating: 5,
        review: "⭐⭐⭐⭐⭐ Mabilis at maayos ang paggawa. Salamat po!",
      },
      {
        title: "Install Wall-Mounted TV",
        category: "assembly",
        description: "Need help mounting a 55-inch TV on a concrete wall. Bracket provided.",
        location: "Makati City, Metro Manila",
        budget: 700,
        posterId: "seed-client-2",
        posterName: "Mang Tonyo",
        posterAvatar: "https://randomuser.me/api/portraits/men/32.jpg",
        datePosted: serverTimestamp(),
        status: "completed",
        imageUrl: "https://images.unsplash.com/photo-1541976590-713941681591?ixlib=rb-4.0.3&auto=format&fit=crop&w=500&q=80",
        assignedTaskerId: "seed-tasker-7",
        assignedOfferId: "dummy-offer-7",
        rating: 4,
        review: "⭐⭐⭐⭐ Okay ang service, medyo late lang ng 15 mins. Pero maganda ang pagkakabit.",
      },
      {
        title: "Personal Shopper for Clothes",
        category: "other",
        description: "Need a personal shopper to help pick out clothes for an event. 3 hours.",
        location: "BGC, Taguig City",
        budget: 1200,
        posterId: "seed-client-3",
        posterName: "Liza Soberano",
        posterAvatar: "https://randomuser.me/api/portraits/women/2.jpg",
        datePosted: serverTimestamp(),
        status: "completed",
        imageUrl: "https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?ixlib=rb-4.0.3&auto=format&fit=crop&w=500&q=80",
        assignedTaskerId: "seed-tasker-6",
        assignedOfferId: "dummy-offer-8",
        rating: 5,
        review: "⭐⭐⭐⭐⭐ Super galing pumili! Ang daming magagandang options. Thank you!",
      },
      {
        title: "Car Wash (Home Service)",
        category: "cleaning",
        description: "Full exterior and interior car wash for a sedan. Home service needed.",
        location: "Paranaque City, Metro Manila",
        budget: 600,
        posterId: "seed-client-4",
        posterName: "Daniel Padilla",
        posterAvatar: "https://randomuser.me/api/portraits/men/4.jpg",
        datePosted: serverTimestamp(),
        status: "completed",
        imageUrl: "https://images.unsplash.com/photo-1581578731548-c646952?ixlib=rb-4.0.3&auto=format&fit=crop&w=500&q=80",
        assignedTaskerId: "seed-tasker-2",
        assignedOfferId: "dummy-offer-9",
        rating: 4,
        review: "⭐⭐⭐⭐ Malinis ang kotse ko, pero medyo matagal matapos. Still good!",
      },
      {
        title: "Repair Broken Window Pane",
        category: "repairs",
        description: "Small window pane is cracked, needs replacement. Glass will be provided.",
        location: "Quezon City, Metro Manila",
        budget: 700,
        posterId: "seed-client-5",
        posterName: "Kathryn Bernardo",
        posterAvatar: "https://randomuser.me/api/portraits/women/6.jpg",
        datePosted: serverTimestamp(),
        status: "completed",
        imageUrl: "https://images.unsplash.com/photo-1581093458791-8a6b5d174d6c?ixlib=rb-4.0.3&auto=format&fit=crop&w=500&q=80",
        assignedTaskerId: "seed-tasker-1",
        assignedOfferId: "dummy-offer-10",
        rating: 5,
        review: "⭐⭐⭐⭐⭐ Very professional at mabilis mag-ayos. Safe na ulit ang bahay!",
      },
      {
        title: "Move Small Furniture",
        category: "moving",
        description: "Move a small sofa and a coffee table from 1st floor to 2nd floor. Within the same house.",
        location: "Pasig City, Metro Manila",
        budget: 500,
        posterId: "seed-client-6",
        posterName: "Alden Richards",
        posterAvatar: "https://randomuser.me/api/portraits/men/8.jpg",
        datePosted: serverTimestamp(),
        status: "completed",
        imageUrl: "https://images.unsplash.com/photo-1541976590-713941681591?ixlib=rb-4.0.3&auto=format&fit=crop&w=500&q=80",
        assignedTaskerId: "seed-tasker-9",
        assignedOfferId: "dummy-offer-11",
        rating: 5,
        review: "⭐⭐⭐⭐⭐ Malakas at maingat sa gamit. Salamat sa tulong!",
      },
      {
        title: "Garden Landscaping",
        category: "gardening",
        description: "Need help with basic garden landscaping and plant trimming for a small backyard.",
        location: "Tagaytay City, Cavite",
        budget: 1800,
        posterId: "seed-client-11",
        posterName: "Bea Alonzo",
        posterAvatar: "https://randomuser.me/api/portraits/women/16.jpg",
        datePosted: serverTimestamp(),
        status: "open",
        imageUrl: "https://images.unsplash.com/photo-1518568779000-74057686079d?ixlib=rb-4.0.3&auto=format&fit=crop&w=500&q=80",
      },
      {
        title: "Pet Sitting for a Weekend",
        category: "other",
        description: "Looking for a reliable pet sitter for my cat over the weekend. Includes feeding and playtime.",
        location: "San Juan City, Metro Manila",
        budget: 1000,
        posterId: "seed-client-12",
        posterName: "John Lloyd Cruz",
        posterAvatar: "https://randomuser.me/api/portraits/men/18.jpg",
        datePosted: serverTimestamp(),
        status: "open",
        imageUrl: "https://images.unsplash.com/photo-1514888627710-900000000000?ixlib=rb-4.0.3&auto=format&fit=crop&w=500&q=80",
      },
      {
        title: "Marketing Consultation",
        category: "marketing",
        description: "Need a marketing expert for a 1-hour consultation on social media strategy for a small business.",
        location: "Online (Philippines)",
        budget: 2500,
        posterId: "seed-client-13",
        posterName: "Sarah Geronimo",
        posterAvatar: "https://randomuser.me/api/portraits/women/18.jpg",
        datePosted: serverTimestamp(),
        status: "open",
        imageUrl: "https://images.unsplash.com/photo-1557804506-669a67965da0?ixlib=rb-4.0.3&auto=format&fit=crop&w=500&q=80",
      },
      {
        title: "Web Development Help",
        category: "other",
        description: "Looking for a freelance web developer to help fix some bugs on my React website. Hourly rate.",
        location: "Remote (Philippines)",
        budget: 3000,
        posterId: "seed-client-14",
        posterName: "Gerald Anderson",
        posterAvatar: "https://randomuser.me/api/portraits/men/20.jpg",
        datePosted: serverTimestamp(),
        status: "open",
        imageUrl: "https://images.unsplash.com/photo-1542831371-29b0f74f94dd?ixlib=rb-4.0.3&auto=format&fit=crop&w=500&q=80",
      },
      {
        title: "Event Photography",
        category: "other",
        description: "Need a photographer for a small birthday party (3 hours).",
        location: "Pasig City, Metro Manila",
        budget: 4000,
        posterId: "seed-client-15",
        posterName: "Maja Salvador",
        posterAvatar: "https://randomuser.me/api/portraits/women/20.jpg",
        datePosted: serverTimestamp(),
        status: "open",
        imageUrl: "https://images.unsplash.com/photo-1520342868574-5fa38041646e?ixlib=rb-4.0.3&auto=format&fit=crop&w=500&q=80",
      },
      {
        title: "Home Network Setup",
        category: "repairs",
        description: "Help setting up a new home network, including router configuration and Wi-Fi optimization.",
        location: "Quezon City, Metro Manila",
        budget: 900,
        posterId: "seed-client-16",
        posterName: "Dingdong Dantes",
        posterAvatar: "https://randomuser.me/api/portraits/men/22.jpg",
        datePosted: serverTimestamp(),
        status: "open",
        imageUrl: "https://images.unsplash.com/photo-1526374965328-ad571f7203a6?ixlib=rb-4.0.3&auto=format&fit=crop&w=500&q=80",
      },
      {
        title: "Deep Cleaning for Bathroom",
        category: "cleaning",
        description: "Thorough cleaning and sanitization of one bathroom. Focus on tiles and grout.",
        location: "Mandaluyong City, Metro Manila",
        budget: 700,
        posterId: "seed-client-17",
        posterName: "Marian Rivera",
        posterAvatar: "https://randomuser.me/api/portraits/women/24.jpg",
        datePosted: serverTimestamp(),
        status: "open",
        imageUrl: "https://images.unsplash.com/photo-1581578731548-c646952?ixlib=rb-4.0.3&auto=format&fit=crop&w=500&q=80",
      },
      {
        title: "Furniture Repair (Chair Leg)",
        category: "repairs",
        description: "One chair leg is wobbly, needs to be re-secured or replaced.",
        location: "Makati City, Metro Manila",
        budget: 300,
        posterId: "seed-client-18",
        posterName: "Dennis Trillo",
        posterAvatar: "https://randomuser.me/api/portraits/men/24.jpg",
        datePosted: serverTimestamp(),
        status: "open",
        imageUrl: "https://images.unsplash.com/photo-1541976590-713941681591?ixlib=rb-4.0.3&auto=format&fit=crop&w=500&q=80",
      },
      {
        title: "Grocery Shopping & Delivery",
        category: "delivery",
        description: "Full grocery list for a family of four, delivered to home. Approx. 2 hours shopping time.",
        location: "Taguig City, Metro Manila",
        budget: 600,
        posterId: "seed-client-19",
        posterName: "Jennylyn Mercado",
        posterAvatar: "https://randomuser.me/api/portraits/women/26.jpg",
        datePosted: serverTimestamp(),
        status: "open",
        imageUrl: "https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?ixlib=rb-4.0.3&auto=format&fit=crop&w=500&q=80",
      },
      {
        title: "Wall Mounting for Picture Frames",
        category: "assembly",
        description: "Mount 5 picture frames on a living room wall. Need a drill and level.",
        location: "Pasig City, Metro Manila",
        budget: 400,
        posterId: "seed-client-20",
        posterName: "Tom Rodriguez",
        posterAvatar: "https://randomuser.me/api/portraits/men/26.jpg",
        datePosted: serverTimestamp(),
        status: "open",
        imageUrl: "https://images.unsplash.com/photo-1541976590-713941681591?ixlib=rb-4.0.3&auto=format&fit=crop&w=500&q=80",
      },
    ];

    for (const task of initialTasks) {
      await addDoc(tasksCollectionRef, task);
    }
    toast.info("Initial demo tasks added!");
  }
};